version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/aaron7/eventstore
    steps:
      - checkout
      - run: make dep
      - run: make test
      - run: make build
      - run: make integration-tests
