version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13-buster
    working_directory: /go/src/github.com/aaron7/eventstore
    steps:
      - checkout
      - run: make test
      - run: make build
      - run: sudo apt-get -y install python3 python3-pip
      - run: pip3 install --user -r /go/src/github.com/aaron7/eventstore/integration-tests/python/requirements.txt
      - run: make integration-tests
